alias p="pnpm"
alias cm="cd ~/Developer/Work/UP/mono/"
alias cs="cd ~/Developer/sandbox/"
alias sa="cd ~/Developer/OS/Sealant/"
alias wr="cd ~/Developer/Work/Webroot/"
alias n="nvim"
alias lg="lazygit"
alias c="claude --dangerously-skip-permissions"

if command -v eza >/dev/null 2>&1; then
  alias l="eza --icons=always"
  alias la="eza -a --icons=always"
  alias lh="eza -ad --icons=always .*"
  alias ll="eza -lg --icons=always"
  alias lla="eza -lag --icons=always"
  alias llh="eza -lagd --icons=always .*"
  alias ls="eza --icons=always"
  alias lt2="eza -lTg --level=2 --icons=always"
  alias lt3="eza -lTg --level=3 --icons=always"
  alias lt4="eza -lTg --level=4 --icons=always"
  alias lt="eza -lTg --icons=always"
  alias lta2="eza -lTag --level=2 --icons=always"
  alias lta3="eza -lTag --level=3 --icons=always"
  alias lta4="eza -lTag --level=4 --icons=always"
  alias lta="eza -lTag --icons=always"
fi
